//##################################################################
//说明：该文件由typescript-box编译器自动生成，请不要手工修改
//This file is generated by the compiler. Please do not modify it manually.
//安装：(How to install) npm install -g typescript-box
//##################################################################

//项目库文件:Project library file
//项目类文件:Project classed file
///<reference path="../src/geom/Point.ts" />
///<reference path="../src/geom/Ray.ts" />
///<reference path="../src/geom/Matrix.ts" />
///<reference path="../src/geom/Space.ts" />
///<reference path="../src/geom/IntersectResult.ts" />
///<reference path="../src/geom/SimpleIntersectResult.ts" />
///<reference path="../src/geom/Shape.ts" />
///<reference path="../src/geom/IGeom.ts" />
///<reference path="../src/geom/Geom.ts" />
///<reference path="../src/lens/ILens.ts" />
///<reference path="../src/lens/Lens.ts" />
///<reference path="../src/geom/Circle.ts" />
///<reference path="../src/OpticalWorld.ts" />
///<reference path="../src/lens/VVLens.ts" />
///<reference path="../src/lens/CCLens.ts" />
///<reference path="../src/lens/CFLens.ts" />
///<reference path="../src/geom/Circle2.ts" />
///<reference path="../src/lens/CVLens.ts" />
///<reference path="../src/geom/Ellipse.ts" />
///<reference path="../src/Example01.ts" />
///<reference path="../src/lens/FCLens.ts" />
///<reference path="../src/lens/FVLens.ts" />
///<reference path="../src/geom/Hyperbola.ts" />
///<reference path="../src/geom/Line.ts" />
///<reference path="../src/geom/Line2.ts" />
///<reference path="../src/geom/Parabola.ts" />
///<reference path="../src/geom/Segment.ts" />
///<reference path="../src/lens/VCLens.ts" />
///<reference path="../src/lens/VFLens.ts" />
//files count:29	(v20180720 . by Sunnyboxs (ts-version:2.9.2))