//##################################################################
//说明：该文件由typescript-box编译器自动生成，请不要手工修改
//This file is generated by the compiler. Please do not modify it manually.
//安装：(How to install) npm install -g typescript-box
//##################################################################

//项目库文件:Project library file
//项目类文件:Project classed file
///<reference path="../src/HObject.ts" />
///<reference path="../src/elecData/DTerminal.ts" />
///<reference path="../src/elecData/DTwoTerminalElement.ts" />
///<reference path="../src/graph/Vertex.ts" />
///<reference path="../src/graph/Edge.ts" />
///<reference path="../src/ElectricityCalculater.ts" />
///<reference path="../src/ElectricityWorld.ts" />
///<reference path="../src/examples/Example01.ts" />
//files count:8	(v20180720 . by Sunnyboxs (ts-version:2.9.2))