var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
//##################################################################
//说明：该文件由typescript-box编译器自动生成，请不要手工修改
//This file is generated by the compiler. Please do not modify it manually.
//安装：(How to install) npm install -g typescript-box
//##################################################################
//项目库文件:Project library file
//项目类文件:Project classed file
///<reference path="../src/HObject.ts" />
///<reference path="../src/elecData/DTerminal.ts" />
///<reference path="../src/elecData/DTwoTerminalElement.ts" />
///<reference path="../src/graph/Vertex.ts" />
///<reference path="../src/graph/Edge.ts" />
///<reference path="../src/ElectricityCalculater.ts" />
///<reference path="../src/ElectricityWorld.ts" />
///<reference path="../src/examples/Example01.ts" />
//files count:8	(v20180720 . by Sunnyboxs (ts-version:2.9.2))
/**
 * Created by hanyeah on 2019/8/12.
 */
var hanyeah;
(function (hanyeah) {
    var electricity;
    (function (electricity) {
        var HObject = /** @class */ (function () {
            function HObject() {
                this.UID = HObject.TIME + (HObject.COUNTING++);
            }
            HObject.prototype.destroy = function () {
                //
            };
            HObject.COUNTING = 1;
            HObject.TIME = 0; // new Date().getTime();
            return HObject;
        }());
        electricity.HObject = HObject;
    })(electricity = hanyeah.electricity || (hanyeah.electricity = {}));
})(hanyeah || (hanyeah = {}));
/**
 * Created by hanyeah on 2019/8/13.
 */
var hanyeah;
(function (hanyeah) {
    var electricity;
    (function (electricity) {
        var elecData;
        (function (elecData) {
            var DTerminal = /** @class */ (function (_super) {
                __extends(DTerminal, _super);
                function DTerminal() {
                    var _this = _super.call(this) || this;
                    _this.root = _this;
                    _this.root2 = _this;
                    _this.prev = _this;
                    _this.next = _this;
                    return _this;
                }
                Object.defineProperty(DTerminal.prototype, "root", {
                    get: function () {
                        if (this._root._root !== this._root) {
                            var root = this._root;
                            var temp = void 0;
                            while (root !== root._root) {
                                root = root._root;
                            }
                            var son = this;
                            while (son !== root) {
                                temp = son._root;
                                son._root = root;
                                son = temp;
                            }
                        }
                        return this._root;
                    },
                    set: function (terminal) {
                        this._root = terminal;
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(DTerminal.prototype, "root2", {
                    get: function () {
                        if (this._root2._root2 !== this._root2) {
                            var root = this._root2;
                            var temp = void 0;
                            while (root !== root._root2) {
                                root = root._root2;
                            }
                            var son = this;
                            while (son !== root) {
                                temp = son._root2;
                                son._root2 = root;
                                son = temp;
                            }
                        }
                        return this._root2;
                    },
                    set: function (terminal) {
                        this._root2 = terminal;
                    },
                    enumerable: true,
                    configurable: true
                });
                DTerminal.prototype.destroy = function () {
                    _super.prototype.destroy.call(this);
                    this.disConnect();
                    this.root = null;
                    this.root2 = null;
                    this.prev = null;
                    this.next = null;
                };
                DTerminal.prototype.connect = function (terminal) {
                    if (this.root !== terminal.root) {
                        var next1 = this.next;
                        var next2 = terminal.next;
                        this.next = next2;
                        next2.prev = this;
                        terminal.next = next1;
                        next1.prev = terminal;
                        this.root.root = terminal.root;
                    }
                };
                DTerminal.prototype.disConnect = function () {
                    if (this.root === this) {
                        var nextV = this.next;
                        while (nextV !== this) {
                            nextV.root = this.next;
                            nextV = nextV.next;
                        }
                    }
                    this.root = this;
                    var next = this.next;
                    var prev = this.prev;
                    prev.next = next;
                    next.prev = prev;
                    this.next = this;
                    this.prev = this;
                };
                return DTerminal;
            }(electricity.HObject));
            elecData.DTerminal = DTerminal;
        })(elecData = electricity.elecData || (electricity.elecData = {}));
    })(electricity = hanyeah.electricity || (hanyeah.electricity = {}));
})(hanyeah || (hanyeah = {}));
/**
 * Created by hanyeah on 2019/8/13.
 */
var hanyeah;
(function (hanyeah) {
    var electricity;
    (function (electricity) {
        var elecData;
        (function (elecData) {
            var DTwoTerminalElement = /** @class */ (function (_super) {
                __extends(DTwoTerminalElement, _super);
                function DTwoTerminalElement() {
                    var _this = _super.call(this) || this;
                    _this.SI = 0;
                    _this.SU = 0;
                    _this.U = 0;
                    _this.I = 0;
                    _this.R = 0;
                    _this.C = 0;
                    _this.L = 0;
                    _this.isBreak = false;
                    _this.isShortCircuit = false;
                    _this._terminal0 = new elecData.DTerminal();
                    _this._terminal1 = new elecData.DTerminal();
                    return _this;
                }
                Object.defineProperty(DTwoTerminalElement.prototype, "terminal0", {
                    get: function () {
                        return this._terminal0;
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(DTwoTerminalElement.prototype, "terminal1", {
                    get: function () {
                        return this._terminal1;
                    },
                    enumerable: true,
                    configurable: true
                });
                DTwoTerminalElement.prototype.destroy = function () {
                    _super.prototype.destroy.call(this);
                    this._terminal0.destroy();
                    this._terminal1.destroy();
                    this._terminal0 = null;
                    this._terminal1 = null;
                };
                DTwoTerminalElement.prototype.repair = function () {
                    this.isBreak = false;
                    this.isShortCircuit = false;
                };
                return DTwoTerminalElement;
            }(electricity.HObject));
            elecData.DTwoTerminalElement = DTwoTerminalElement;
        })(elecData = electricity.elecData || (electricity.elecData = {}));
    })(electricity = hanyeah.electricity || (hanyeah.electricity = {}));
})(hanyeah || (hanyeah = {}));
/**
 * Created by hanyeah on 2019/8/12.
 */
///<reference path="../HObject.ts" />
var hanyeah;
(function (hanyeah) {
    var electricity;
    (function (electricity) {
        var graph;
        (function (graph) {
            var Vertex = /** @class */ (function (_super) {
                __extends(Vertex, _super);
                function Vertex() {
                    return _super.call(this) || this;
                }
                return Vertex;
            }(electricity.HObject));
            graph.Vertex = Vertex;
        })(graph = electricity.graph || (electricity.graph = {}));
    })(electricity = hanyeah.electricity || (hanyeah.electricity = {}));
})(hanyeah || (hanyeah = {}));
/**
 * Created by hanyeah on 2019/8/12.
 */
var hanyeah;
(function (hanyeah) {
    var electricity;
    (function (electricity) {
        var graph;
        (function (graph) {
            var Edge = /** @class */ (function (_super) {
                __extends(Edge, _super);
                function Edge() {
                    var _this = _super.call(this) || this;
                    _this.vertex1 = new graph.Vertex();
                    _this.vertex2 = new graph.Vertex();
                    return _this;
                }
                return Edge;
            }(electricity.HObject));
            graph.Edge = Edge;
        })(graph = electricity.graph || (electricity.graph = {}));
    })(electricity = hanyeah.electricity || (hanyeah.electricity = {}));
})(hanyeah || (hanyeah = {}));
/**
 * Created by hanyeah on 2019/8/13.
 */
var hanyeah;
(function (hanyeah) {
    var electricity;
    (function (electricity) {
        var Edge = hanyeah.electricity.graph.Edge;
        var Vertex = hanyeah.electricity.graph.Vertex;
        var ElectricityCalculater = /** @class */ (function () {
            function ElectricityCalculater() {
            }
            ElectricityCalculater.prototype.calculate = function (elements) {
                var len = elements.length;
                var ele;
                var terminal0;
                var terminal1;
                // -------------root2-------------
                for (var i = 0; i < len; i++) {
                    ele = elements[i];
                    ele.terminal0.root2 = ele.terminal0.root;
                    ele.terminal1.root2 = ele.terminal1.root;
                }
                // ------------顶点合并-----------
                for (var i = 0; i < len; i++) {
                    ele = elements[i];
                    if (ele.isShortCircuit) {
                        terminal0 = ele.terminal0.root2;
                        terminal1 = ele.terminal1.root2;
                        if (terminal0 !== terminal1) {
                            terminal0.root2 = terminal1;
                        }
                    }
                }
                // ------------生成顶点Map---------
                var vertexMap = {};
                for (var i = 0; i < len; i++) {
                    ele = elements[i];
                    terminal0 = ele.terminal0.root2;
                    terminal1 = ele.terminal1.root2;
                    if (!vertexMap[terminal0.UID]) {
                        vertexMap[terminal0.UID] = new Vertex();
                    }
                    if (!vertexMap[terminal1.UID]) {
                        vertexMap[terminal1.UID] = new Vertex();
                    }
                }
                // ------------生成边Map------------
                var edgeMap = {};
                for (var i = 0; i < len; i++) {
                    ele = elements[i];
                    if (ele.isBreak) {
                        continue;
                    }
                    terminal0 = ele.terminal0.root2;
                    terminal1 = ele.terminal1.root2;
                    if (terminal0 !== terminal1) {
                        edgeMap[ele.UID] = new Edge();
                    }
                }
                // console.log(vertexMap);
                // console.log(edgeMap);
            };
            return ElectricityCalculater;
        }());
        electricity.ElectricityCalculater = ElectricityCalculater;
    })(electricity = hanyeah.electricity || (hanyeah.electricity = {}));
})(hanyeah || (hanyeah = {}));
/**
 * Created by hanyeah on 2019/8/12.
 */
var hanyeah;
(function (hanyeah) {
    var electricity;
    (function (electricity) {
        var ElectricityWorld = /** @class */ (function (_super) {
            __extends(ElectricityWorld, _super);
            function ElectricityWorld() {
                var _this = _super.call(this) || this;
                _this.calculater = new electricity.ElectricityCalculater();
                _this.elements = [];
                return _this;
            }
            ElectricityWorld.prototype.hasElement = function (element) {
                return this.elements.indexOf(element) !== -1;
            };
            ElectricityWorld.prototype.addElement = function (element) {
                if (!this.hasElement(element)) {
                    this.elements.push(element);
                }
            };
            ElectricityWorld.prototype.removeElement = function (element) {
                var ind = this.elements.indexOf(element);
                if (ind !== -1) {
                    this.elements.splice(ind, 1);
                }
            };
            ElectricityWorld.prototype.calculate = function () {
                this.calculater.calculate(this.elements);
            };
            return ElectricityWorld;
        }(electricity.HObject));
        electricity.ElectricityWorld = ElectricityWorld;
    })(electricity = hanyeah.electricity || (hanyeah.electricity = {}));
})(hanyeah || (hanyeah = {}));
/**
 * Created by hanyeah on 2019/8/13.
 */
var hanyeah;
(function (hanyeah) {
    var electricity;
    (function (electricity) {
        var examples;
        (function (examples) {
            var DTwoTerminalElement = hanyeah.electricity.elecData.DTwoTerminalElement;
            var Example01 = /** @class */ (function () {
                function Example01(ctx) {
                    var elecWorld = new electricity.ElectricityWorld();
                    var arr = [];
                    for (var i = 0; i < 10000; i++) {
                        var ele = new DTwoTerminalElement();
                        elecWorld.addElement(ele);
                        arr.push(ele);
                    }
                    arr[0].terminal0.connect(arr[1].terminal0);
                    arr[0].terminal0.connect(arr[2].terminal0);
                    arr[0].terminal1.connect(arr[1].terminal1);
                    arr[0].terminal1.connect(arr[2].terminal1);
                    // console.log(arr);
                    var loop = function () {
                        elecWorld.calculate();
                        requestAnimationFrame(loop);
                    };
                    requestAnimationFrame(loop);
                }
                return Example01;
            }());
            examples.Example01 = Example01;
        })(examples = electricity.examples || (electricity.examples = {}));
    })(electricity = hanyeah.electricity || (hanyeah.electricity = {}));
})(hanyeah || (hanyeah = {}));
